### ISSUE TITLE
Unable to connect to the voice call: timed out waiting for peer connection

### ISSUE THREAD

**Issue by davide-prade** [mattermost/mattermost-mobile#7349]
#### Summary
Cannot start/join to call

### Environment Information
  - Device Name: HUAWEI Mate 20 lite
  - OS Version: EMUI 12.0.0
  - Mattermost App Version: 2.4.0 (Build 6000465)
  - Mattermost Server Version: 7.9.2 (self-hosted)

#### Steps to reproduce
1. Open Mattermost app
2. Start call

#### Expected behavior
Calls started/joined successfully.

#### Observed behavior (that appears unintentional)
Cannot start/join the voice call. The following error appears: "**Unable to connect to the voice call: timed out waiting for peer connection**".
![Screenshot_20230516_121130](https://github.com/mattermost/mattermost-mobile/assets/22656675/f0c44ea3-5cf9-4584-8982-12dd958f2e19)

#### Possible fixes
No fix found.

**Comment by cpoile** [comment]
@amyblais It's likely not related to the mobile release specifically, so no need for it to impact.

Hi @davide-prade , this error is seen when the mobile calls client cannot reach the Calls plugin or rtcd service, so it's a networking issue. You would need to debug the connection. For example: Are you able to connect to a call using the webapp or desktop? If so, is the mobile device on the exact same wifi as the webapp/desktop that works?

**Comment by davide-prade** [comment]
Hi @cpoile, voice calls works correctly with desktop app end/or web browser. 
I have tried also on the same wifi connection and the error is the same.

**Comment by davide-prade** [comment]
Yes, I have also tried to start a call from mobile app.
I tried on the cellular data and also on the same wifi network. The error is the same.

**Comment by cpoile** [comment]
1. Are you able to check on a different Android or Apple phone?
1. Can you give details of the networking setup for your MM server? (firewalls, load balancers, etc.)

**Comment by davide-prade** [comment]
>    1. Are you able to check on a different Android or Apple phone?

Today I tried again with a colleague of mine at work with desktop app and he cannot initiate a call, while I can. Last days it was the other way around.
On the same wifi network I can establish a call, but only from the webapp and/or desktop app.
At the moment I have no other mobile devices on which to try.


>     2. Can you give details of the networking setup for your MM server? (firewalls, load balancers, etc.)

The version of Mattemost is the one included in the Docker image of GitLab CE.

```yaml
version: '3.7'

services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: '.........'
    container_name: gitlab-ce
    environment:
      GITLAB_OMNIBUS_CONFIG: |
#       .........
        mattermost_external_url 'https://mattermost.anydata.it'
#       .........
    ports:
#       .........
      - '8443:8443/udp'
#       .........
    volumes:
#       .........
    networks:
      - 'gitlab'

#.........

networks:
  gitlab:
    name: gitlab-network
```

The ISP firewall has opened the 8443/UDP port and there is an ISP DNAT that redirects 8443/UDP traffic from public IP to internal VM IP. There are no load balancers.
